name: flutter_live
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  synchronized: any
  universal_platform: any #通用平台检测,因为谷歌官方屏蔽了web上的dart:io,直接调用Platform.isAndroid之类的方法会报错
  path: any

flutter:
  plugin:
    platforms:
      android:
        package: com.xgs.flutter_live
        pluginClass: FlutterLivePlugin
      ios:
        pluginClass: FlutterLivePlugin
